### ISSUE TITLE
Is this your own modified version of PyImageSearch's people counter tutorial

### ISSUE THREAD

**Issue by 4nakin** [mustafaali96/people-counter-pyimage#1]
Hi,

Is there any advantages of this project vs the original source on the Pyimage tutorial ? 
How do I run this project?

**Comment by mustafaali96** [comment]
Slightly different from the original one, i've created temp txt file to count total person inside the shop and plot live graph. 

Some ui template also used.In people_counter.py file commands are written to run the program.

In graph folder there is a file graph.py you'll have to run it explicitly. (Default port will be used to open on chrome)

**Comment by 4nakin** [comment]
What is your hardware spec. I am using Jetson Nano with GPU on, and running the original Pyimage code, the performance is not good when having multiple person with higher walking speed.

**Comment by mustafaali96** [comment]
Hardware spec. i7 16GB RAM GPU GTX1060 6GB, performance was pretty fine but that's true sometimes it miss persons with high walking speed.
Check your usage if its 80% you can drop the FPS manually, or train your own MobileNet SSD model with less number of classes.
I'm not sure but try changing (maxDisappeared, maxDistance) parameter from pyimagesearch/centroidtracker.py  file.
